### ISSUE TITLE
Lack of Verification in MarkovChain.__init__

### ISSUE THREAD

**Issue by kameranis** [Mandragorian/simple-markov#12]
It seems that I can create a MarkovChain instance with 

```
initial_distribution = {'0': 1, '1': 2}
transition_table = {'0': [('0', 1), ('1', 2)], '1': [('0', 3), ('1', 4)] }
```

This can be dealt two ways.

a) Declare these to be impossible and raise an Error
b) Normalize, so that the values are relative weights

I expect your timely response

**Comment by VHarisop** [comment]
You generally don't want to normalize - it gracefully conceals typos when running:

```
initial_distro = {'0': 0.05, '1': 0.905}  # which of the two is wrong?
```

On the other hand, if input is to be validated, floating point hell breaks loose:

```
$ python3
>>> ((1/2 + 1/3) + 1/6) == 1
False
>>> (1/2 + (1/3 + 1/6)) == 1
True
```

It's either ugly checks for floating point precision:

```
abs(sum(i for i in values) - 1) < eps
```

or we could enforce fractional (or string) format in the probability vectors and use [fractions](https://docs.python.org/3.5/library/fractions.html) instead.

```
>>> Fraction(1, 2) + Fraction(1, 3) + Fraction(1, 6)
Fraction(1, 1)
```

**Comment by kameranis** [comment]
For that there is `numpy.isclose` and `numpy.allclose`
It is floating point precision, but I don't think that anyone uses precision greater than 6 digits.
Meaning: It doesn't have to be perfect, it has to be good.

**Comment by Mandragorian** [comment]
Thanks for reporting this. #14 is a partial fix for this issue. 

However in the future please refrain from any expectations, particularly regarding timely responses, since this a side project developed in our spare time.

Also it appears that you already had a fix in mind while opening this issue. So the next time consider fixing it yourself and PR'ing the changes. This will also help with any expectations you might have.

**Comment by Mandragorian** [comment]
#14 was merged (and now fully addresses tha lack of initialization checks).
